[project]
name = "backend"
version = "0.1.0"
description = "NASA-SAC back-end layer for the Cosmobras48 team's web platform" 
readme = "README.md"
requires-python = ">=3.12"

authors =[
    { name = "Guilherme Gonçalves (lwglg)", email = "lwglguilherme@gmail.com" },
]

dependencies = [
    "dependency-injector>=4.48.2",
    "fastapi>=0.118.0",
    "fastapi-filter>=2.0.1",
    "mongoengine>=0.29.1",
    "pydantic>=2.11.10",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "swagger-ui-py>=25.7.1",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = []
